apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: user-service
          image: galethus/user-service:latest
          ports:
            - containerPort: 443
              name: user-service
          resources:
            requests:
              cpu: 1m
              memory: 200Mi
            limits:
              cpu: 1000m
              memory: 512Mi
          volumeMounts:
            - name: tls-certs
              mountPath: "/etc/ssl/certs"
              readOnly: true
      volumes:
        - name: tls-certs
          secret:
            secretName: tls-secret # Ensure this matches your Secret's name

---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  ports:
    - port: 443
      targetPort: 443
  selector:
    app: user-service

---
apiVersion: v1
kind: Secret
metadata:
  name: tls-secret
type: kubernetes.io/tls
data:
  tls.crt: |-
    $(cat certs/cert.base64)
  tls.key: |-
    $(cat certs/key.base64)
