apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: user-service
          image: galethus/user-service:latest
          ports:
            - containerPort: 8080
              name: user-service
          resources:
            requests:
              cpu: 1m
              memory: 200Mi
            limits:
              cpu: 1000m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: user-service
