services:
  user-service:
    image: galethus/user-service
    container_name: user-service
    ports:
      - "5000:8080"
      - "5001:443"
    build:
      context: .
      dockerfile: UserService/Dockerfile
      tags:
        - "galethus/user-service:test"
    networks: 
      - arkade

networks:
  arkade:
    name: arkade
    driver: bridge