apiVersion: apps/v1
kind: Deployment
metadata:
  name: review-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: review-service
  template:
    metadata:
      labels:
        app: review-service
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: review-service
          image: galethus/review-service:latest
          ports:
            - containerPort: 5002
              name: review-service
          resources:
            requests:
              cpu: 1m
              memory: 200Mi
            limits:
              cpu: 1000m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: review-service
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: review-service
