name: User Service CI

on:
  push:
    branches:
      - main
      - development
      - config/ci
defaults:
    run:
      working-directory: ./UserService
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x

      - name: Restore NuGet packages
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x

      - name: Restore NuGet packages
        run: dotnet restore

      - name: Test
        run: dotnet test --no-restore

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Deployment step
        run: echo "Define your deployment script!"
      # Add additional steps for deployment as needed
